name: zs6d
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.7
  - pip
  - pip:
    - tqdm==4.65.0
    - timm==0.9.16
    - matplotlib==3.8.3
    - scikit-learn==1.4.1.post1
    - opencv-python==4.9.0
    - git+https://github.com/lucasb-eyer/pydensecrf.git@dd070546eda51e21ab772ee6f14807c7f5b1548b
    - transforms3d==0.4.1
    - pillow==9.4.0
    - plyfile==1.0.3
    - trimesh==4.1.4
    - imageio==2.34.0
    - pypng==0.20220715.0
    - vispy==0.12.2
    - pyopengl==3.1.1a1
    - pyglet==1.2.4
    - numba==0.59.0
    - jupyter==1.0.0
